###################################################
# REQUARKS WIKI - CONFIGURATION                   #
###################################################

# -------------------------------------------------
# Title of this site
# -------------------------------------------------

title: Wiki

# -------------------------------------------------
# Full path to the site, without the trailing slash
# -------------------------------------------------

host: http://localhost

# -------------------------------------------------
# Port the server should listen to (80 by default)
# -------------------------------------------------
# To use process.env.PORT, comment the line below:

port: 80

# -------------------------------------------------
# Data Directories
# -------------------------------------------------

datadir:
  repo: ./repo
  db: ./data
  uploads: ./uploads

# -------------------------------------------------
# Git Connection Info
# -------------------------------------------------
# Full explanation + examples in the documentation (https://requarks-wiki.readme.io/)

git:
  path: auto
  mode: remote
  url: https://github.com/Organization/Repo
  auth:
    type: ssh
    user: gitusername
    publickey: /etc/requarkswiki/keys/git.pub
    privatekey: /etc/requarkswiki/keys/git.key
    passphrase: SomeSshPassphrase
  # auth:
  #   type: oauth
  #   token: 1234567890abcdefghijklmnopqrstuvxyz
  # auth:
  #   type: basic
  #   user: johnsmith
  #   pass: password123

# -------------------------------------------------
# Secret key to use when encrypting sessions
# -------------------------------------------------
# Use a long and unique random string (256-bit keys are perfect!)

sessionSecret: 1234567890abcdefghijklmnopqrstuvxyz

# -------------------------------------------------
# Administrator email
# -------------------------------------------------
# An account will be created using the email specified here.
# The password is set to "admin123" by default. Change it immediately upon login!!!

admin: admin@company.com