#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full documentation + examples:
# https://docs.requarks.io/wiki/install

# ---------------------------------------------------------------------
# Port the main server should listen to
# ---------------------------------------------------------------------

port: 80

# ---------------------------------------------------------------------
# Data Directories
# ---------------------------------------------------------------------

paths:
  repo: ./repo
  data: ./data

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# PostgreSQL 9.5 or later required

db:
  host: localhost
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki

# ---------------------------------------------------------------------
# Redis
# ---------------------------------------------------------------------
# Redis 3.2 or later required

redis:
  host: localhost
  port: 6379
  db: 0
  password: null

# ---------------------------------------------------------------------
# Log Level
# ---------------------------------------------------------------------
# Possible values: error, warn, info (default), verbose, debug, silly

logLevel: info

# ---------------------------------------------------------------------
# Configuration Mode
# ---------------------------------------------------------------------
# Possible values: auto (default), file, setup

configMode: auto

# ---------------------------------------------------------------------
# Background Workers
# ---------------------------------------------------------------------
# Leave 0 for auto based on CPU cores

workers: 0

# ---------------------------------------------------------------------
# High Availability
# ---------------------------------------------------------------------
# Read the docs BEFORE changing these settings!

ha:
  node: primary
  readonly: false
